//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using Example2.Contracts.Payments;


namespace Example2.Accounting
{
    public partial class ContractCreatedEventHandler : IHandleMessages<ContractCreatedEvent>
    {
		
		public void Handle(ContractCreatedEvent message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(ContractCreatedEvent message);

        public IBus Bus { get; set; }

    }

	
}
