//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using Example1.Internal.Commands.Payments;


namespace Example1.Payments
{
    public partial class PlaceOrderCommandSender : IPlaceOrderCommandSender, ServiceMatrix.Shared.INServiceBusComponent
    {
		
        public void Send(PlaceOrderCommand message)
        {
            ConfigurePlaceOrderCommand(message);
            Bus.Send(message);
        }

        partial void ConfigurePlaceOrderCommand(PlaceOrderCommand message);

        public IBus Bus { get; set; }

    }

	
	public partial interface IPlaceOrderCommandSender
    {
        
        void Send(PlaceOrderCommand message);

	}

	
}
