//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using Example3.Internal.Commands.Payments;


namespace Example3.Payments
{
    public partial class PlaceOrderCommandHandler : IPlaceOrderCommandHandler, ServiceMatrix.Shared.INServiceBusComponent, IHandleMessages<PlaceOrderCommand>
    {
		
		public void Handle(PlaceOrderCommand message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(PlaceOrderCommand message);

        public void Send(CreateInvoiceCommand message)
        {
            ConfigureCreateInvoiceCommand(message);
            Bus.Send(message);
        }

        partial void ConfigureCreateInvoiceCommand(CreateInvoiceCommand message);

        public IBus Bus { get; set; }

    }

	
	public partial interface IPlaceOrderCommandHandler
    {
        
        void Send(CreateInvoiceCommand message);

	}

	
}
