

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using NServiceBus;

using Example3.Internal.Commands.Payments;


using Example3.Payments;
	

namespace Example3.UI.Controllers
{
    public partial class TestMessagesController : Controller
    {
        //
        // GET: /TestMessages/

        public ActionResult Index()
        {
            return View();
        }

				
		public IPlaceOrderCommandSender PlaceOrderCommandSender { get; set; }
		
        // POST: /TestMessages/SendMessagePlaceOrderCommand
          
        [HttpPost]
        public string SendMessagePlaceOrderCommand(PlaceOrderCommand PlaceOrderCommand)
        {
            ConfigurePlaceOrderCommand(PlaceOrderCommand);
            PlaceOrderCommandSender.Send(PlaceOrderCommand);
			return "<p> PlaceOrderCommand command sent</p>";
        }
		
	  


	  // Send Commands
    
        partial void ConfigurePlaceOrderCommand(PlaceOrderCommand message);
      
	 // Publish Events
        }
}
