//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using Example1.Internal.Commands.Payments;


namespace Example1.Payments
{
    public partial class PlaceOrderCommandHandler : IHandleMessages<PlaceOrderCommand>
    {
		
		public void Handle(PlaceOrderCommand message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(PlaceOrderCommand message);

        public IBus Bus { get; set; }

    }

	
}
