//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using Example3.Contracts.Payments;
using NServiceBus.Saga;


namespace Example3.PremiumMembership
{
    public partial class Membership : Saga<MembershipSagaData>, IAmStartedByMessages<ContractCreatedEvent>, IHandleMessages<InvoiceSentToCollection>
    {
		
		public void Handle(ContractCreatedEvent message)
		{
			// Store message in Saga Data for later use
			this.Data.ContractCreatedEvent = message;
			// Handle message on partial class
			this.HandleImplementation(message);

			// Check if Saga is Completed 
			CheckIfAllMessagesReceived();
		}

		public void Handle(InvoiceSentToCollection message)
		{
			// Store message in Saga Data for later use
			this.Data.InvoiceSentToCollection = message;
			// Handle message on partial class
			this.HandleImplementation(message);

			// Check if Saga is Completed 
			CheckIfAllMessagesReceived();
		}

		partial void HandleImplementation(ContractCreatedEvent message);

		partial void HandleImplementation(InvoiceSentToCollection message);

        public void CheckIfAllMessagesReceived()
        {
            if (this.Data.ContractCreatedEvent != null && this.Data.InvoiceSentToCollection != null)
            {
                AllMessagesReceived();
            }
        }

        partial void AllMessagesReceived();
     }

     public partial class MembershipSagaData : IContainSagaData
     {
           public virtual Guid Id { get; set; }
           public virtual string Originator { get; set; }
           public virtual string OriginalMessageId { get; set; }

           public virtual ContractCreatedEvent ContractCreatedEvent { get; set; }
           public virtual InvoiceSentToCollection InvoiceSentToCollection { get; set; }

    }

	
}
